/**
 * Datos Iniciales y Semilla para España (Mock Seed Data)
 * Previncendios España
 */

import {
  Municipality,
  EmergencyEvent,
  EmergencyAlert,
  OperationalResource,
  ResourceRequest,
  VolunteerProfile,
  PatrolLocation,
  BandoMessage,
  DocumentAttachment,
  ActivityLog,
  SystemSettings,
} from '../types';

export const initialMunicipalities: Municipality[] = [
  {
    id: 'muni_el_tiemblo',
    name: 'El Tiemblo',
    ineCode: '05241',
    province: 'Ávila',
    autonomousCommunity: 'Castilla y León',
    centerLat: 40.3801,
    centerLng: -4.4395,
    fireRiskLevel: 'Extremo',
    activeEmergencyCount: 2,
    officialContactPhone: '+34 918 62 50 02',
    emergencyEmail: 'emergencias@eltiemblo.es',
    twinnedMunicipalityIds: ['muni_cebreros', 'muni_san_martin'],
    population: 4300,
    createdAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 'muni_cebreros',
    name: 'Cebreros',
    ineCode: '05057',
    province: 'Ávila',
    autonomousCommunity: 'Castilla y León',
    centerLat: 40.4552,
    centerLng: -4.4632,
    fireRiskLevel: 'Muy Alto',
    activeEmergencyCount: 1,
    officialContactPhone: '+34 918 63 00 10',
    emergencyEmail: 'proteccioncivil@cebreros.es',
    twinnedMunicipalityIds: ['muni_el_tiemblo'],
    population: 3100,
    createdAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 'muni_ronda',
    name: 'Ronda',
    ineCode: '29084',
    province: 'Málaga',
    autonomousCommunity: 'Andalucía',
    centerLat: 36.7423,
    centerLng: -5.1671,
    fireRiskLevel: 'Extremo',
    activeEmergencyCount: 1,
    officialContactPhone: '+34 952 87 32 40',
    emergencyEmail: 'seguridad@ronda.es',
    twinnedMunicipalityIds: [],
    population: 33600,
    createdAt: '2026-01-12T10:00:00Z',
  },
  {
    id: 'muni_cazorla',
    name: 'Cazorla',
    ineCode: '23028',
    province: 'Jaén',
    autonomousCommunity: 'Andalucía',
    centerLat: 37.9133,
    centerLng: -3.0019,
    fireRiskLevel: 'Alto',
    activeEmergencyCount: 0,
    officialContactPhone: '+34 953 72 00 00',
    emergencyEmail: 'ayuntamiento@cazorla.es',
    twinnedMunicipalityIds: [],
    population: 7400,
    createdAt: '2026-01-15T12:00:00Z',
  },
  {
    id: 'muni_ourense',
    name: 'Ourense',
    ineCode: '32054',
    province: 'Ourense',
    autonomousCommunity: 'Galicia',
    centerLat: 42.3364,
    centerLng: -7.8636,
    fireRiskLevel: 'Moderado',
    activeEmergencyCount: 1,
    officialContactPhone: '+34 988 38 81 00',
    emergencyEmail: 'emergencias@ourense.gal',
    twinnedMunicipalityIds: [],
    population: 104000,
    createdAt: '2026-02-01T09:00:00Z',
  },
  {
    id: 'muni_chiva',
    name: 'Chiva',
    ineCode: '46111',
    province: 'Valencia',
    autonomousCommunity: 'Comunitat Valenciana',
    centerLat: 39.4721,
    centerLng: -0.7188,
    fireRiskLevel: 'Alto',
    activeEmergencyCount: 1,
    officialContactPhone: '+34 961 80 00 00',
    emergencyEmail: 'proteccioncivil@chiva.es',
    twinnedMunicipalityIds: [],
    population: 16000,
    createdAt: '2026-02-05T11:00:00Z',
  },
];

export const initialEmergencyEvents: EmergencyEvent[] = [
  {
    id: 'evt-001',
    title: 'Foco Activo en Reserva Valle Iruelas',
    type: 'incendio_forestal',
    severity: 'Nivel 2',
    status: 'confirmado',
    municipalityId: 'muni_el_tiemblo',
    municipalityName: 'El Tiemblo',
    province: 'Ávila',
    latitude: 40.3842,
    longitude: -4.4328,
    locationDescription: 'Paraje Castañar de El Tiemblo, ladera suroeste cerca de la pista de Iruelas.',
    description: 'Foco de incendio forestal activo en pinar de pino albar con rápido avance impulsado por rachas de viento del Suroeste a 30 km/h. Se movilizan dos medios aéreos y retén terrestre.',
    reportedByUid: 'usr-vol-01',
    reportedByName: 'Carlos Fernández (Voluntario Tiemblo)',
    reportedByRole: 'voluntario',
    source: 'voluntario',
    assignedBrigade: 'Brigada INFOCAL B-04 + Retén Municipal',
    photoUrls: [
      'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80',
    ],
    affectedAreaHectares: 18.5,
    createdAt: '2026-07-28T09:30:00Z',
    updatedAt: '2026-07-28T11:45:00Z',
  },
  {
    id: 'evt-002',
    title: 'Foco Secundario por Chispas en Puerto Arrebatacapas',
    type: 'incendio_forestal',
    severity: 'Nivel 1',
    status: 'en_control',
    municipalityId: 'muni_cebreros',
    municipalityName: 'Cebreros',
    province: 'Ávila',
    latitude: 40.4512,
    longitude: -4.4619,
    locationDescription: 'Carretera AV-504 km 8.2 en pinar con matorral.',
    description: 'Reproducción menor por chispas desplazadas. Atacada tempranamente por patrulla de voluntarios con batefuegos y autobomba ligera.',
    reportedByUid: 'usr-ayto-cebreros',
    reportedByName: 'Oficial Protección Civil Cebreros',
    reportedByRole: 'ayuntamiento',
    source: 'ayuntamiento',
    assignedBrigade: 'Autobomba Cebreros AB-01',
    photoUrls: [],
    affectedAreaHectares: 2.1,
    createdAt: '2026-07-28T10:15:00Z',
    updatedAt: '2026-07-28T11:20:00Z',
  },
  {
    id: 'evt-003',
    title: 'Riesgo Extremo por Ola de Calor y Pinar en Serranía',
    type: 'ola_calor',
    severity: 'Nivel 1',
    status: 'detectado',
    municipalityId: 'muni_ronda',
    municipalityName: 'Ronda',
    province: 'Málaga',
    latitude: 36.7412,
    longitude: -5.1631,
    locationDescription: 'Serranía de Ronda, accesos al Parque Nacional Sierra de las Nieves.',
    description: 'Temperaturas extremas de 41.2ºC con humedad del 14%. Se activa dispositivo de vigilancia reforzada y cierre temporal de senderos de alto riesgo.',
    reportedByUid: 'usr-ayto-ronda',
    reportedByName: 'Concejalía de Seguridad Ronda',
    reportedByRole: 'ayuntamiento',
    source: 'ayuntamiento',
    assignedBrigade: 'Patrulla INFOCA Ronda',
    photoUrls: [],
    affectedAreaHectares: 0,
    createdAt: '2026-07-28T08:00:00Z',
    updatedAt: '2026-07-28T08:00:00Z',
  },
  {
    id: 'evt-004',
    title: 'Aviso por Tormenta Seca con Rayos en Cañón del Sil',
    type: 'tormenta',
    severity: 'Nivel 0',
    status: 'detectado',
    municipalityId: 'muni_ourense',
    municipalityName: 'Ourense',
    province: 'Ourense',
    latitude: 42.3481,
    longitude: -7.8631,
    locationDescription: 'Ribeira Sacra, laderas de monte bajo.',
    description: 'Actividad eléctrica detectada por radar AEMET sin precipitación apreciable. Posibilidad de incendios por rayo durmiente.',
    reportedByUid: 'usr-sat-firms',
    reportedByName: 'Sistema Satelital FIRMS',
    reportedByRole: 'superadmin',
    source: 'satelite_firms',
    assignedBrigade: 'Vigilancia Mantenimiento DGT/Xunta',
    photoUrls: [],
    affectedAreaHectares: 0,
    createdAt: '2026-07-28T10:00:00Z',
    updatedAt: '2026-07-28T10:00:00Z',
  },
  {
    id: 'evt-005',
    title: 'Inundación Preventiva Barranco de Chiva',
    type: 'inundacion',
    severity: 'Nivel 1',
    status: 'en_control',
    municipalityId: 'muni_chiva',
    municipalityName: 'Chiva',
    province: 'Valencia',
    latitude: 39.4721,
    longitude: -0.7188,
    locationDescription: 'Barranco del Chiva a la entrada de la urbanización Olimar.',
    description: 'Caudal elevado acumulado por tormenta previa. Limpieza de imbornales y desvío con sacos de arena.',
    reportedByUid: 'usr-vol-02',
    reportedByName: 'Protección Civil Chiva',
    reportedByRole: 'voluntario',
    source: 'voluntario',
    assignedBrigade: 'Brigada Municipal Chiva',
    photoUrls: [],
    affectedAreaHectares: 0,
    createdAt: '2026-07-28T07:30:00Z',
    updatedAt: '2026-07-28T09:00:00Z',
  },
];

export const initialAlerts: EmergencyAlert[] = [
  {
    id: 'alt-001',
    title: 'EVACUACIÓN PREVENTIVA: Urbanización La Atalaya y Camping Iruelas',
    message: 'Por la proximidad del fuego en Valle Iruelas y cambio de viento, se decreta evacuación de la Urbanización La Atalaya hacia el Polideportivo Municipal de El Tiemblo. Sigan indicaciones de Policía Local y Guardia Civil.',
    type: 'evacuacion',
    severity: 'critica',
    municipalityId: 'muni_el_tiemblo',
    municipalityName: 'El Tiemblo',
    radiusKm: 5.0,
    issuedByUid: 'usr-ayto-tiemblo',
    issuedByName: 'Alcaldía de El Tiemblo / Protección Civil',
    emergencyEventId: 'evt-001',
    isActive: true,
    createdAt: '2026-07-28T11:00:00Z',
  },
  {
    id: 'alt-002',
    title: 'Prohibición Total de Quemas y Uso de Maquinaria Agrícola en Cebreros',
    message: 'Se prohíbe el uso de barbacoas, radiales, desbrozadoras y maquinaria en terreno forestal y franja de 400m hasta nuevo aviso por riesgo Extremo AEMET.',
    type: 'bando_informativo',
    severity: 'alta',
    municipalityId: 'muni_cebreros',
    municipalityName: 'Cebreros',
    radiusKm: 10.0,
    issuedByUid: 'usr-ayto-cebreros',
    issuedByName: 'Ayuntamiento de Cebreros',
    isActive: true,
    createdAt: '2026-07-28T08:30:00Z',
  },
  {
    id: 'alt-003',
    title: 'Alerta Roja Meteorológica por Temperatura Extrema en Serranía de Ronda',
    message: 'Evite actividades al aire libre entre las 12:00 y las 19:00h. Puntos de hidratación habilitados en el Centro de Salud y Ayuntamiento.',
    type: 'alerta_roja',
    severity: 'alta',
    municipalityId: 'muni_ronda',
    municipalityName: 'Ronda',
    radiusKm: 15.0,
    issuedByUid: 'usr-ayto-ronda',
    issuedByName: 'Ayuntamiento de Ronda',
    isActive: true,
    createdAt: '2026-07-28T09:00:00Z',
  },
];

export const initialResources: OperationalResource[] = [
  {
    id: 'res-001',
    name: 'Camión Autobomba Forestal BRL-01 (4000L)',
    category: 'autobomba',
    status: 'movilizado',
    municipalityId: 'muni_el_tiemblo',
    municipalityName: 'El Tiemblo',
    capacityOrQuantity: '4.000 Litros Agua + Triturador',
    latitude: 40.3821,
    longitude: -4.4360,
    contactPerson: 'Jefe de Dotación Gómez',
    contactPhone: '+34 600 11 22 33',
    updatedAt: '2026-07-28T10:00:00Z',
  },
  {
    id: 'res-002',
    name: 'Retén Terrestre Voluntarios Bravo',
    category: 'reten_terrestre',
    status: 'movilizado',
    municipalityId: 'muni_el_tiemblo',
    municipalityName: 'El Tiemblo',
    capacityOrQuantity: '8 Operativos capacitados con Pulaski y Gorgui',
    latitude: 40.3835,
    longitude: -4.4345,
    contactPerson: 'Coordinador Voluntarios Marcos',
    contactPhone: '+34 611 22 33 44',
    updatedAt: '2026-07-28T10:15:00Z',
  },
  {
    id: 'res-003',
    name: 'Punto de Recarga de Agua - Balsa Los Toros',
    category: 'punto_agua',
    status: 'disponible',
    municipalityId: 'muni_el_tiemblo',
    municipalityName: 'El Tiemblo',
    capacityOrQuantity: '120.000 Litros (Apta para Helicóptero Bambi Bucket)',
    latitude: 40.3750,
    longitude: -4.4250,
    contactPerson: 'Guardería Forestal',
    contactPhone: '+34 622 33 44 55',
    updatedAt: '2026-07-28T08:00:00Z',
  },
  {
    id: 'res-004',
    name: 'Refugio de Emergencia - Polideportivo Municipal',
    category: 'refugio_albergue',
    status: 'disponible',
    municipalityId: 'muni_el_tiemblo',
    municipalityName: 'El Tiemblo',
    capacityOrQuantity: '150 Camas de campaña, cocina y climatización',
    latitude: 40.3808,
    longitude: -4.4421,
    contactPerson: 'Servicios Sociales El Tiemblo',
    contactPhone: '+34 918 62 50 02',
    updatedAt: '2026-07-28T11:10:00Z',
  },
  {
    id: 'res-005',
    name: 'Vehículo 4x4 NISSAN PickUp con Motobomba Ligera (Cebreros)',
    category: 'vehiculo_moteado',
    status: 'disponible',
    municipalityId: 'muni_cebreros',
    municipalityName: 'Cebreros',
    capacityOrQuantity: '600 Litros de Agua + mangueras 25mm',
    latitude: 40.4552,
    longitude: -4.4632,
    contactPerson: 'Jefe Protección Civil Cebreros',
    contactPhone: '+34 633 44 55 66',
    updatedAt: '2026-07-28T09:00:00Z',
  },
  {
    id: 'res-006',
    name: 'Dron de Inspección Térmica Matrice 300 RTK',
    category: 'dron',
    status: 'disponible',
    municipalityId: 'muni_cebreros',
    municipalityName: 'Cebreros',
    capacityOrQuantity: 'Cámara infrarroja 640x512 y zoom 200x',
    latitude: 40.4560,
    longitude: -4.4640,
    contactPerson: 'Piloto Certificado Juan A.',
    contactPhone: '+34 644 55 66 77',
    updatedAt: '2026-07-28T09:30:00Z',
  },
];

export const initialResourceRequests: ResourceRequest[] = [
  {
    id: 'req-001',
    requestingMunicipalityId: 'muni_el_tiemblo',
    requestingMunicipalityName: 'El Tiemblo',
    targetMunicipalityId: 'muni_cebreros',
    targetMunicipalityName: 'Cebreros',
    resourceTypeNeeded: 'Vehículo 4x4 con Motobomba Ligera + Dron Térmico',
    quantityNeeded: '1 Unidad 4x4 + 1 Dron',
    urgencyLevel: 'alta',
    status: 'aceptada',
    notes: 'Cesión urgente para vigilancia nocturna de flanco norte en Valle Iruelas.',
    createdAt: '2026-07-28T10:45:00Z',
  },
];

export const initialVolunteerProfiles: VolunteerProfile[] = [
  {
    uid: 'usr-vol-01',
    userName: 'Carlos Fernández Gómez',
    municipalityId: 'muni_el_tiemblo',
    municipalityName: 'El Tiemblo',
    province: 'Ávila',
    phone: '+34 611 22 33 44',
    email: 'carlos.voluntario@tiemblo.es',
    groupOrAssociation: 'Agrupación de Voluntarios de Protección Civil El Tiemblo',
    vehicleType: 'Todoterreno Toyota Hilux 4x4',
    has4x4: true,
    hasChainsaw: true,
    hasWaterPump: true,
    hasFirstAidCertification: true,
    epiComplete: true,
    radioEquipment: 'Transceptor Walkie VHF/UHF Banderas Protección Civil',
    actionRadiusKm: 25,
    isAvailableNow: true,
    availabilitySchedule: 'Disponibilidad Inmediata 24/7',
    assignedPatrolZone: 'Sector 1 - Valle Iruelas',
    trainings: [
      'Curso Básico de Incendios Forestales (CBIF)',
      'Primeros Auxilios y Soporte Vital Básico (SVB)',
      'Capacitación en Manejo Seguro de Motosierra y Troncos',
      'Conducción Evasiva Off-Road 4x4',
    ],
    trainingHours: 120,
    vehicleDetails: 'Cabina doble, Bola de remolque 3500kg, Bola de arrastre y Winch delantero 5T',
    toolsList: ['Batefuegos', 'Azada Pulaski', 'Herramienta Gorgui', 'Mochila Extintora 20L', 'Motosierra Husqvarna 550XP'],
    notes: 'Voluntario referente para aperturas de fajas cortafuegos y coordinación de brigadas de primera intervención.',
    updatedAt: '2026-07-28T09:00:00Z',
  },
  {
    uid: 'usr-vol-02',
    userName: 'María Elena Soria',
    municipalityId: 'muni_cebreros',
    municipalityName: 'Cebreros',
    province: 'Ávila',
    phone: '+34 622 33 44 55',
    email: 'maria.soria@cebreros.org',
    groupOrAssociation: 'Retén de Apoyo Agrícola y Forestal Cebreros',
    vehicleType: 'Furgón Ligero 4WD con Tanque Auxiliar',
    has4x4: true,
    hasChainsaw: false,
    hasWaterPump: true,
    hasFirstAidCertification: true,
    epiComplete: true,
    radioEquipment: 'Walkie PMR446 / Tetrapol',
    actionRadiusKm: 15,
    isAvailableNow: true,
    availabilitySchedule: 'Tardes, Noches y Fines de Semana',
    assignedPatrolZone: 'Sector 2 - Carretera AV-504',
    trainings: [
      'Primeros Auxilios Sanitarios y Avituallamiento en Emergencias',
      'Operador de Motobomba de Extinción',
    ],
    trainingHours: 60,
    vehicleDetails: 'Furgón con depósito de agua 500L y mangueras de 25mm',
    toolsList: ['Mochila Extintora 20L', 'Batefuegos', 'Botiquín de Rescate AVAC'],
    notes: 'Disponibilidad especial para puntos de avituallamiento, atención sanitaria inicial y puestos de radio.',
    updatedAt: '2026-07-28T09:15:00Z',
  },
];

export const initialPatrolLocations: PatrolLocation[] = [
  {
    id: 'patrol-01',
    uid: 'usr-vol-01',
    userName: 'Patrulla Voluntarios Tiemblo-1',
    role: 'voluntario',
    municipalityId: 'muni_el_tiemblo',
    latitude: 40.3831,
    longitude: -4.4370,
    speedKmH: 12,
    statusNote: 'Realizando rondas de observación con prismáticos en Pista Alta.',
    timestamp: '2026-07-28T11:40:00Z',
  },
  {
    id: 'patrol-02',
    uid: 'usr-vol-02',
    userName: 'Patrulla Cebreros-Vigilancia',
    role: 'voluntario',
    municipalityId: 'muni_cebreros',
    latitude: 40.4530,
    longitude: -4.4600,
    speedKmH: 25,
    statusNote: 'Patrullando franja perimetral en AV-504.',
    timestamp: '2026-07-28T11:35:00Z',
  },
];

export const initialMessages: BandoMessage[] = [
  {
    id: 'msg-001',
    senderUid: 'usr-ayto-tiemblo',
    senderName: 'Alcaldía de El Tiemblo',
    senderRole: 'ayuntamiento',
    municipalityId: 'muni_el_tiemblo',
    municipalityName: 'El Tiemblo',
    title: 'BANDO OFICIAL: Activación del Plan de Emergencia Municipal (PEMU) Nivel 2',
    content: 'Queda constituido el CECOPAL en el Ayuntamiento de El Tiemblo. Se solicita a todos los vecinos mantener la calma, informarse únicamente por canales oficiales y mantener libres los accesos a la carretera de Iruelas para los vehículos de extinción.',
    channel: 'bando_oficial',
    targetRoles: ['ciudadano', 'voluntario', 'ayuntamiento', 'invitado'],
    createdAt: '2026-07-28T09:45:00Z',
  },
  {
    id: 'msg-002',
    senderUid: 'usr-ayto-tiemblo',
    senderName: 'Coordinación de Protección Civil Tiemblo',
    senderRole: 'ayuntamiento',
    municipalityId: 'muni_el_tiemblo',
    municipalityName: 'El Tiemblo',
    title: 'INSTRUCCIÓN TÉCNICA: Convocatoria de Voluntarios acreditados en Polideportivo',
    content: 'Todos los voluntarios registrados con vehículo 4x4 y acreditación nivel B deben presentarse a las 12:30h en la puerta sur del Polideportivo para asignación de tareas logísticas y reparto de equipos de radio.',
    channel: 'instruccion_voluntarios',
    targetRoles: ['voluntario'],
    createdAt: '2026-07-28T10:30:00Z',
  },
];

export const initialDocuments: DocumentAttachment[] = [
  {
    id: 'doc-001',
    title: 'Plan de Emergencia Municipal ante Incendios Forestales (PEMU 2026)',
    category: 'plan_emergencia',
    municipalityId: 'muni_el_tiemblo',
    fileUrl: '#',
    fileSize: '4.2 MB (PDF)',
    uploadedBy: 'Ayuntamiento de El Tiemblo',
    isPublic: true,
    createdAt: '2026-01-15T10:00:00Z',
  },
  {
    id: 'doc-002',
    title: 'Mapa de Puntos de Agua y Vías de Evacuación El Tiemblo',
    category: 'ficha_operativa',
    municipalityId: 'muni_el_tiemblo',
    fileUrl: '#',
    fileSize: '8.1 MB (PDF)',
    uploadedBy: 'Protección Civil',
    isPublic: false,
    createdAt: '2026-03-10T11:20:00Z',
  },
  {
    id: 'doc-003',
    title: 'Protocolo de Actuación para Voluntarios de Protección Civil en conflagración',
    category: 'protocolo',
    municipalityId: 'muni_cebreros',
    fileUrl: '#',
    fileSize: '2.5 MB (PDF)',
    uploadedBy: 'Superadministración Nacional',
    isPublic: true,
    createdAt: '2026-02-01T09:00:00Z',
  },
];

export const initialActivityLogs: ActivityLog[] = [
  {
    id: 'log-001',
    userUid: 'usr-ayto-tiemblo',
    userName: 'Ayuntamiento El Tiemblo',
    userRole: 'ayuntamiento',
    municipalityId: 'muni_el_tiemblo',
    action: 'CREAR_ALERTA',
    targetCollection: 'alerts',
    targetDocId: 'alt-001',
    details: 'Emitida alerta de Evacuación preventiva en Urbanización La Atalaya',
    ipAddress: '194.224.18.12',
    timestamp: '2026-07-28T11:00:00Z',
  },
  {
    id: 'log-002',
    userUid: 'usr-vol-01',
    userName: 'Carlos Fernández',
    userRole: 'voluntario',
    municipalityId: 'muni_el_tiemblo',
    action: 'NOTIFICAR_INCIDENCIA',
    targetCollection: 'emergencyEvents',
    targetDocId: 'evt-001',
    details: 'Notificada incidencia forestal con foto en Valle Iruelas',
    ipAddress: '88.12.94.3',
    timestamp: '2026-07-28T09:30:00Z',
  },
  {
    id: 'log-003',
    userUid: 'usr-ayto-tiemblo',
    userName: 'Ayuntamiento El Tiemblo',
    userRole: 'ayuntamiento',
    municipalityId: 'muni_el_tiemblo',
    action: 'SOLICITAR_RECURSO',
    targetCollection: 'resourceRequests',
    targetDocId: 'req-001',
    details: 'Solicitud de apoyo de vehículo 4x4 y dron enviada a Ayuntamiento Cebreros',
    ipAddress: '194.224.18.12',
    timestamp: '2026-07-28T10:45:00Z',
  },
];

export const initialSystemSettings: SystemSettings = {
  id: 'global-settings',
  platformName: 'Previncendios España',
  maintenanceMode: false,
  firmsApiEnabled: true,
  aemetApiEnabled: true,
  autoAlertDistanceKm: 10,
  updatedAt: '2026-07-28T12:00:00Z',
};
